apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns3-simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns3-simulation
  template:
    metadata:
      labels:
        app: ns3-simulation
    spec:
      containers:
      - name: ns3-container
        image: hadilbouasker/ns3-app:v10.8
        command: ["/usr/bin/tini","--","python3","automate_sim_with_UE.py"]
        resources:
          requests:
            memory: "500Mi"   
            cpu: "1"      
          limits:
            memory: "5Gi"   
            cpu: "4" 
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 3600








